AY2122S2-CS2103T-T11-2/tp

docs/DeveloperGuide.md, docs/_config.yml, docs/_sass/minima/_base.scss
1. Preliminary use cases
2. User stories
3. Target user profile
4. Value proposition
These are not final.
Help review thanks!
=> Add use cases and user stories

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
=> Conform to Checkstyle for the FindCommand Changes

docs/UserGuide.md
* Now, the specified format has been changed to the latest version
* E.g. `find n/Alex Yeo`
* Added the various fields available to find by E.g. `e/`
To include error handling for the `find` command
=> Update the find command in User Guide

docs/DeveloperGuide.md
=> Edit DeveloperGuide Glossary

docs/UserGuide.md
The UserGuide contains the function of the function it currently has and
the functions to be implemented in the following iteration.
=> Update UserGuide to include the function of sort

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AppointmentCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/RemarkCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/client/Appointment.java, src/main/java/seedu/address/model/client/Client.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedClient.java, src/main/java/seedu/address/ui/ClientCard.java, src/main/resources/view/ClientListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedClientTest.java, src/test/java/seedu/address/testutil/ClientBuilder.java, src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java, src/test/java/seedu/address/testutil/TypicalClients.java
Users now can add an appointment command to indicate if they have a
meeting and the date of the meeting. The appointment time is accurate
to the minute for now.
The format of this command is 'appointment INDEX time/yyyy-MM-dd-HH-mm'.
=> Add appointment command

src/main/java/seedu/address/model/buyer/Buyer.java, src/main/java/seedu/address/model/buyer/UniqueBuyerList.java, src/main/java/seedu/address/model/client/Client.java
A buyer will have the following additional fields on top of a regular client:
- `propertiesToBuy`
=> Add Buyer class

src/main/java/seedu/address/model/buyer/Buyer.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/buyer/BuyerTest.java, src/test/java/seedu/address/model/buyer/UniqueBuyerListTest.java, src/test/java/seedu/address/testutil/BuyerBuilder.java, src/test/java/seedu/address/testutil/TypicalBuyers.java
Currently, many of the tests are similar to Clients since the underlying functionality is still the same.
In the future, will use stubs and abstract the instantiations to CommandTestUtil Class.
=> Add Buyer test cases

src/main/java/seedu/address/logic/commands/AddSellerCommand.java, src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java, src/main/java/seedu/address/model/seller/Seller.java, src/main/java/seedu/address/model/seller/UniqueSellerList.java
Added new seller class, including addSeller commands
=> Add Seller class

docs/UserGuide.md, docs/team/wjunhong.md
1. I have added the `addbuyer` command to the UG and provided some sample examples of how to use it
2. I have updated my PPP to reflect my contributions for v1.2
=> Update PPP and UG

src/main/java/seedu/address/logic/commands/AppointmentCommand.java, src/main/java/seedu/address/model/client/Appointment.java, src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
fixed typo and added some tests
=> Add some test cases with a little typo fixed

docs/team/wjunhong.md
Some trailing whitespace was found in my PPP. I have removed them
Help to check thanks!
=> Remove trailing whitespace

docs/team/chuashihong.md
=> Branch update ppp

build.gradle, src/main/java/seedu/address/logic/commands/ExitCommand.java
=> Enable assertions

build.gradle, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/model/property/PriceRange.java, src/test/java/seedu/address/model/buyer/BuyerTest.java, src/test/java/seedu/address/model/property/PriceRangeTest.java, src/test/java/seedu/address/model/property/PropertyToBuyTest.java, src/test/java/seedu/address/model/property/PropertyToSellTest.java, src/test/java/seedu/address/model/seller/SellerTest.java
PriceRange.
PriceRange's validity was checked when it is instantiated.
That is not desirable as we need to assert many exceptions when creating
test cases involving PriceRange.
PriceRange checks validity similar to the checks on Client Phone.
That is, we use checkArgument and static isValidPriceRange separately,
which is more effective.
=> Branch price range constructor edit

src/main/java/seedu/address/ui/ClientCard.java, src/main/java/seedu/address/ui/ClientListPanel.java
Fixed some incorrect variable names causing null pointer exception
=> Bugfix for Jar file

src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/property/House.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/property/NullPropertyToBuy.java, src/main/java/seedu/address/model/property/PriceRange.java, src/main/java/seedu/address/model/property/PropToBuy.java, src/main/java/seedu/address/model/property/PropertyToBuy.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedBuyer.java, src/main/java/seedu/address/storage/JsonAdaptedPropertyToBuy.java, src/main/java/seedu/address/storage/JsonAdaptedSeller.java, src/main/java/seedu/address/ui/ClientCard.java, src/main/java/seedu/address/ui/PropertyToSellList.java, src/test/java/seedu/address/logic/commands/AddBuyerCommandIntegrationTest.java, src/test/java/seedu/address/testutil/BuyerBuilder.java
-render the Property to UI
-have addProperty Commands
Refactored some naming styles to make it easier to read
```JsonAdaptedPropertyToBuy``` : to make it available to render to ui
-Now can properly be used, but might need to improve in the future
-The address book will automatically save the propertyToBuy in Json Format,
but we haven't implement a way to read JSON file to transform it to model.
example of new JSON format:
```
{
"buyers" : [ {
"name" : "Jacky",
"phone" : "2103",
"appointment" : "",
"tagged" : [ "friends" ],
"propertyToBuy" : "Not a house type"
} ]
}
```
=> Branch fix json

docs/UserGuide.md
Change `add` to `addbuyer`, and other minute details including removing the fields address and email.
=> Update UG. Still needs more update after we implement more.

docs/DeveloperGuide.md
Minor language and structural adjustments to DG
=> Adjust DG content

src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java, src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java, src/main/java/seedu/address/logic/parser/AddPropertyToBuyCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/property/Location.java, src/main/java/seedu/address/model/property/NullPropertyToBuy.java, src/main/java/seedu/address/model/property/PriceRange.java, src/test/java/seedu/address/logic/commands/AddPtbCommandTest.java, src/test/java/seedu/address/logic/parser/AddPtbCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/property/LocationTest.java, src/test/java/seedu/address/model/property/PriceRangeTest.java, src/test/java/seedu/address/testutil/BuyerBuilder.java, src/test/java/seedu/address/testutil/ClientUtil.java
- user can now add a property to buy for a specified buyer
To add a property to buy for a buyer, simply type:
`add-ptb <index> h/housetype l/location pr/val1,val2`
=> Add add-ptb command

docs/DeveloperGuide.md
Initial draft for developer guide updates. Will improve on the quality with subsequent commits.
=> DG initial draft

docs/DeveloperGuide.md, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UiClassDiagram.puml
=> Update Developer Guide

docs/DeveloperGuide.md
- Documentation for `add-ptb` command
- Documentation for `add-pts` command that is yet to be implemented
- Yes the command details are short. This is because they are not finalized and most of the implementation is similar to the above command. I try not to repeat stuff, but might include it for completeness' sake in the future
=> More DG updates

src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java, src/main/java/seedu/address/logic/commands/EditSellerCommand.java, src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java, src/main/java/seedu/address/model/buyer/Buyer.java, src/main/java/seedu/address/model/property/House.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/property/NullPropertyToBuy.java, src/main/java/seedu/address/model/property/NullPropertyToSell.java, src/main/java/seedu/address/model/property/PropertyToSell.java, src/main/java/seedu/address/model/seller/Seller.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedBuyer.java, src/main/java/seedu/address/storage/JsonAdaptedHouse.java, src/main/java/seedu/address/storage/JsonAdaptedPropertyToBuy.java, src/main/java/seedu/address/storage/JsonAdaptedPropertyToSell.java, src/main/java/seedu/address/storage/JsonAdaptedSeller.java, src/main/java/seedu/address/storage/JsonSerializableSellerAddressBook.java, src/main/java/seedu/address/ui/ClientCard.java, src/main/java/seedu/address/ui/SellerCard.java, src/main/resources/view/SellerListCard.fxml, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/storage/JsonAdaptedHouseTest.java, src/test/java/seedu/address/storage/JsonAdaptedPriceRangeTest.java, src/test/java/seedu/address/storage/JsonAdaptedPropertyToSellTest.java, src/test/java/seedu/address/testutil/BuyerBuilder.java, src/test/java/seedu/address/testutil/ClientUtil.java, src/test/java/seedu/address/testutil/SellerBuilder.java
- Commented out some tests to pass the CI
- Now the NullProperty is showing empty string "" in the fields
- Commented out `EditSellerCommandParser` as it is not a complete implementation yet
```
{
{
"buyers" : [ {
"name" : "Jacky",
"phone" : "2103",
"appointment" : "",
"tagged" : [ "friends" ],
"propertyToBuy" : {
"house" : {
"houseType" : "Bungalow",
"location" : "clementi"
},
"priceRange" : {
"lower" : "88888",
"upper" : "99999"
}
}
}, {
"name" : "Jacky2",
"phone" : "2103",
"appointment" : "",
"tagged" : [ "friends" ],
"propertyToBuy" : {
"house" : {
"houseType" : "",
"location" : ""
},
"priceRange" : {
"lower" : "0",
"upper" : "0"
}
}
} ]
}
```
```
{
"sellers" : [ {
"name" : "Jacky",
"phone" : "2103",
"appointment" : "",
"tagged" : [ "friends" ],
"propertyToSell" : {
"house" : { …
```
=> Correct format on saving storage and reading JSON file

src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/BuyerCard.java, src/main/resources/view/SellerListCard.fxml
- Sample data has been updated
- See your favourite individuals like Dara Richard and Chok Hoe as your clients in AgentSee
- Hate them? Delete them! It's that simple!
=> Update sample data

src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/storage/JsonAdaptedHouse.java, src/main/java/seedu/address/storage/JsonAdaptedPropertyToSell.java
- Defensive code for enum method: Prevent access of NULLHOUSETYPE, ensure it can only get called from NullPTS/NullPTB
- Remove redundant code
=> Remove redundant code and add more defensive code

src/main/java/seedu/address/logic/commands/ListBuyerCommand.java, src/main/java/seedu/address/logic/commands/ListSellerCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/ListBuyerCommandTest.java, src/test/java/seedu/address/logic/commands/ListSellerCommandTest.java
Add tests for list-b and list-s
Subsequent commit: remove list when safe
=> Add list-b and list-s

src/main/java/seedu/address/logic/commands/ClearBuyerCommand.java, src/main/java/seedu/address/logic/commands/ClearSellerCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/ClearBuyerCommandTest.java, src/test/java/seedu/address/logic/commands/ClearSellerCommandTest.java
Add tests for clear-b and clear-s
Subsequent commit: remove clear when safe
=> Add clear-b and clear-s

src/test/java/seedu/address/testutil/BuyerBuilder.java, src/test/java/seedu/address/testutil/SellerBuilder.java
Minor update to facilitate testing of functions related to property
Add withProperty methods for Sellerbuilder
Add default constructor for both classes
=> Update SellerBuilder to mirror BuyerBuilder

src/main/java/seedu/address/logic/commands/FindBuyerCommand.java, src/main/java/seedu/address/logic/commands/FindSellerCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindBuyerCommandParser.java, src/main/java/seedu/address/logic/parser/FindSellerCommandParser.java, src/main/java/seedu/address/model/buyer/BuyerLocationContainsKeywordsPredicate.java, src/main/java/seedu/address/model/seller/SellerLocationContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Update prefix to find-s/find-b
Update Find with location prefix
=> Update Find with Location

src/main/java/seedu/address/logic/commands/EditBuyerCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java, src/main/java/seedu/address/model/property/PropertyToBuy.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Update prefix to edit-s/edit-b
=> Update Edit-b to mirror edit-s

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/AddPropertyToBuyCommandParser.java, src/main/java/seedu/address/logic/parser/AddPropertyToSellCommandParser.java, src/main/java/seedu/address/model/property/House.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/property/NullPropertyToBuy.java, src/main/java/seedu/address/model/property/NullPropertyToSell.java, src/main/java/seedu/address/model/property/PropertyToBuy.java, src/main/java/seedu/address/model/property/PropertyToSell.java, src/main/java/seedu/address/model/seller/HasMatchWithBuyerPredicate.java, src/main/java/seedu/address/storage/JsonAdaptedHouse.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/buyer/BuyerHouseTypeContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/buyer/BuyerTest.java, src/test/java/seedu/address/model/property/HouseTest.java, src/test/java/seedu/address/model/property/PropertyToBuyTest.java, src/test/java/seedu/address/model/property/PropertyToSellTest.java, src/test/java/seedu/address/model/seller/HasMatchWithBuyerPredicateTest.java, src/test/java/seedu/address/model/seller/SellerTest.java, src/test/java/seedu/address/storage/JsonAdaptedHouseTest.java, src/test/java/seedu/address/storage/JsonAdaptedPropertyToSellTest.java, src/test/java/seedu/address/testutil/BuyerBuilder.java, src/test/java/seedu/address/testutil/HouseBuilder.java, src/test/java/seedu/address/testutil/SellerBuilder.java
Update UserGuide --> need to check actual website for bugs again
Refactor Location from String to Location class
Refactor ANY to UNSPECIFIED
match can now match buyers of house type UNSPECIFIED to seller with any house type
=> Branch match test userguide update

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditBuyerCommand.java, src/main/java/seedu/address/logic/commands/EditSellerCommand.java, src/main/java/seedu/address/logic/commands/MatchCommand.java, src/main/java/seedu/address/logic/commands/MatchHouseTypeCommand.java, src/main/java/seedu/address/logic/commands/MatchLocationCommand.java, src/main/java/seedu/address/logic/commands/MatchPriceRangeCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java, src/main/java/seedu/address/logic/parser/MatchHouseTypeCommandParser.java, src/main/java/seedu/address/logic/parser/MatchLocationCommandParser.java, src/main/java/seedu/address/logic/parser/MatchPriceRangeCommandParser.java, src/main/java/seedu/address/model/property/Location.java, src/main/java/seedu/address/model/seller/AllFieldsMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/HouseTypeMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/LocationMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/PriceRangeMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/Seller.java, src/main/java/seedu/address/ui/SellerCard.java, src/test/java/seedu/address/model/seller/AllFieldsMatchBuyerPredicateTest.java
Added the following commands, in addition to minor message adjustments, refactoring and editing
=> Add match-h, match-l, match-pr commands

docs/UserGuide.md
- House Type part now has a header for navigation
- Talk details about how to edit the data file
- When the `housetype` is `null` , the application cannot be initialized. Please fix this as soon as possbile
=> Update User guide about Storage

docs/UserGuide.md, src/main/resources/view/MainWindow.fxml
The text for UI that is too long will be hidden and unreadable. Disclaimer in UG
=> Add disclaimer in UG

src/main/java/seedu/address/logic/commands/EditBuyerCommand.java, src/main/java/seedu/address/logic/commands/EditSellerCommand.java
Change the commands such that an exception will be thrown if a user tries to edit property fields, before they add a property.
=> Fix edit-b/s commands

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/AppointmentBuyerCommandParser.java, src/main/java/seedu/address/logic/parser/AppointmentSellerCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
Use 'appt-b INDEX time/reset' to cancel the appointment with a buyer
=> Update appointment command

docs/UserGuide.md
- Formatting for house type & location moved under **Notes**
- Added elaboration for certain choices for `add-ptb`, `add-pts`, `add-b`, `add-s`
=> FIX UG, ADD ELABORATIONS

docs/UserGuide.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java, src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java, src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java, src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java, src/main/java/seedu/address/model/property/PriceRange.java, src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
- explanations about string formatting
- explanations about indexing
- Descriptive error messages
=> More UG explanations, fix error messages

docs/team/wjunhong.md
- I updated my PPP to reflect my contributions, got too much to write so I left out some stuff
- If anything I write wrongly or is yall do one just comment, ill remove it
=> Update PPP Jun Hong

docs/UserGuide.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/EditBuyerCommand.java, src/main/java/seedu/address/logic/commands/MatchCommand.java, src/main/java/seedu/address/logic/commands/MatchHouseTypeCommand.java, src/main/java/seedu/address/logic/commands/MatchLocationCommand.java, src/main/java/seedu/address/logic/commands/MatchPriceRangeCommand.java, src/main/java/seedu/address/logic/parser/AddPropertyToBuyCommandParser.java, src/main/java/seedu/address/logic/parser/AddPropertyToSellCommandParser.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/seller/AllFieldsMatchBuyerPredicate.java, src/main/java/seedu/address/ui/BuyerCard.java, src/main/java/seedu/address/ui/SellerCard.java, src/test/java/seedu/address/testutil/HouseBuilder.java
Fix match index issue #213 where index out of range did not throw an exception previously
#251 where warning was placed at sort instead of clear
#242 user guide updated to say u cannot match null property, and added the code accordingly for that
=> Branch bug fix

docs/UserGuide.md, src/main/java/seedu/address/model/buyer/Buyer.java, src/main/java/seedu/address/model/property/House.java, src/main/java/seedu/address/model/property/HouseType.java, src/main/java/seedu/address/model/property/NullPropertyToBuy.java, src/main/java/seedu/address/model/property/NullPropertyToSell.java, src/main/java/seedu/address/model/property/PropertyToBuy.java, src/main/java/seedu/address/model/property/PropertyToSell.java, src/main/java/seedu/address/model/seller/Seller.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/MatchCommandTest.java
Remove additional house type chunk in UG
Adjust toString messages
Add in all fields for edit message success:
This will be the new edit success message.
=> Fix tag message error to include the spacing as invalid format

src/main/java/seedu/address/model/seller/AllFieldsMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/HouseTypeMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/LocationMatchBuyerPredicate.java, src/main/java/seedu/address/model/seller/PriceRangeMatchBuyerPredicate.java, src/test/java/seedu/address/logic/commands/MatchHouseTypeCommandTest.java, src/test/java/seedu/address/logic/commands/MatchLocationCommandTest.java, src/test/java/seedu/address/logic/commands/MatchPriceRangeCommandTest.java, src/test/java/seedu/address/model/seller/HouseTypeMatchBuyerPredicateTest.java, src/test/java/seedu/address/model/seller/LocationMatchBuyerPredicateTest.java, src/test/java/seedu/address/model/seller/PriceRangeMatchBuyerPredicateTest.java, src/test/java/seedu/address/testutil/PropertyToSellBuilder.java, src/test/java/seedu/address/testutil/TypicalBuyers.java, src/test/java/seedu/address/testutil/TypicalSellers.java
Previously, match command would match buyers to sellers who does not even have a property.
This is now fixed.
Added test cases for the match commands
=> Fix Match commands to not match with sellers who have no property

src/test/java/seedu/address/logic/commands/MatchCommandTest.java, src/test/java/seedu/address/logic/commands/MatchHouseTypeCommandTest.java, src/test/java/seedu/address/logic/commands/MatchLocationCommandTest.java, src/test/java/seedu/address/logic/commands/MatchPriceRangeCommandTest.java, src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java, src/test/java/seedu/address/logic/parser/MatchHouseTypeCommandParserTest.java, src/test/java/seedu/address/logic/parser/MatchLocationCommandParserTest.java, src/test/java/seedu/address/logic/parser/MatchPriceRangeCommandParserTest.java
Added test cases for the parser classes for the match commands, and add exception thrown for match command tests
=> Branch test add

src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/FindBuyerCommandTest.java, src/test/java/seedu/address/logic/commands/FindSellerCommandTest.java, src/test/java/seedu/address/model/buyer/BuyerLocationContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/seller/SellerLocationContainsKeywordsPredicateTest.java
Tests added for:
BuyerLocationContainsKeywordsPredicate
ClearCommandTest
FindBuyerCommand
FindSellerCommand
SellerHouseTypeContainsKeywordsPredicate
SellerLocationContainsKeywordsPredicate
=> Add Tests:

src/test/java/seedu/address/logic/parser/EditBuyerCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditSellerCommandParserTest.java, src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java, src/test/java/seedu/address/testutil/EditSellerDescriptorBuilder.java
Add tests for edit client command parsers and add some setter methods in edit client descriptor classes
=> Add test cases for edit command parsers

docs/DeveloperGuide.md
Formatting fix for user stories
=> Add/edit DG for list-b/list-s, find-b/find-s, clear-b/clear-s/clear-all
